# Generated by Django 4.2.6 on 2024-03-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('val_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField(null=True)),
                ('Question', models.TextField(null=True)),
                ('Answer', models.TextField(null=True)),
                ('Suggested_ans', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('0', 'Disapproved'), (None, 'Not Validated'), ('1', 'Validated')], default=None, max_length=1, null=True)),
            ],
        ),
    ]
