# Generated by Django 4.2.6 on 2024-03-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validation',
            old_name='u_id',
            new_name='U_ID',
        ),
    ]
