# Generated by Django 4.2.6 on 2023-10-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('response', models.CharField(max_length=10000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
