# Generated by Django 4.2.6 on 2023-11-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartquery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='U_ID',
            field=models.IntegerField(null=True),
        ),
    ]
