# Generated by Django 4.2.6 on 2023-11-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartquery', '0002_history_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.CharField(choices=[('0', 'Dis-liked'), (None, 'Not Responded'), ('1', 'Liked')], default=None, max_length=1, null=True),
        ),
    ]
