# Generated by Django 4.2.6 on 2024-03-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempUserMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=95, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('status_toggle', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'base_auth_user',
                'managed': False,
            },
        ),
    ]
