# Generated by Django 4.2.6 on 2024-03-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tempusermaster',
            table='baseusermaster_user',
        ),
    ]
